### ISSUE TITLE
OSGi optional dependency declarations.

### ISSUE THREAD

**Issue by cbutler-am** [gouessej/Ardor3D#15]
The FAQ for Ardor3D says that JInput and SWT are optional, but this is not really true for the OSGi environment because the OSGi metadata for ardor3d-jogl declares imports for packages net.java.games.input and org.eclipse.swt.widgets but does not declare them as optional imports.

This can be corrected simply by declaring &lt;optional&gt;true&lt;/optional&gt; for the jinput and swt artifact dependencies in the Maven pom.xml. The OSGi bundle plugin will then generate optional imports for the used packages.

Note that the JOGAMP gluegen-rt and jogl artifacts are not currently OSGi-enabled, so I'm using locally-wrapped derivatives in my project. Maybe one day JOGAMP will make OSGi-enabled releases of all their artifacts..

**Comment by gouessej** [comment]
I confirm that JInput and SWT are optional. If you don't use the controller based on JInput, you won't need it and it will be replaced by a pure NEWT controller in the future. If you don't use any SWT canvas, you won't need SWT.

There is already a request for enhancement about OSGI here:
https://jogamp.org/bugzilla/show_bug.cgi?id=398

I have to think about the impact of this change, it seems to be reasonable even though I should rather move the classes that depend on SWT into another subproject (maybe ardor3d-swt or another one).

**Comment by gouessej** [comment]
I have decided to move the JInput controller into a separate project (ardor3d-jinput) and the few JOGL SWT canvases into another one (ardor3d-jogl-swt). ardor3d-jogl won't have any dependency on SWT and JInput. I will probably not update the FAQ http://jogamp.org/wiki/index.php/Ardor3D_FAQ but the user's guide will be updated as it explains in details what each sub-project does.

There have been some plans to support OSGI in JogAmp and in "its" most important engines. Please contact Wade on the official IRC channel if you need some information. When it's done in JogAmp, I will do the same for JogAmp's Ardor3D Continuation.

**Comment by gouessej** [comment]
I have just solved half of the problem:
https://github.com/gouessej/Ardor3D/commit/af94ef70aa1c5238db332c655b047cf6f597a5e8

I will solve the other half very soon :)

**Comment by cbutler-am** [comment]
Many thanks, this definitely improves the dependencies for me. As you say, JogAmp also has a little bit of work to do before we have complete OSGi support, but for now my re-packaging of the jogl and gluegen-rt artifacts does the job for my project.

**Comment by gouessej** [comment]
You're welcome. I'll try to fix the rest Sunday.

**Comment by gouessej** [comment]
Sorry for the delay, I've just implemented the missing part of this enhancement:
https://github.com/gouessej/Ardor3D/commit/a21486db32a7075faa7825bded82a65d2fc221bf

I have to update the documentation and the binary build. Enjoy :)
