### ISSUE TITLE
Vector3.hashCode()

### ISSUE THREAD

**Issue by runiter** [gouessej/Ardor3D#24]
Vector3.hashCode seem to be incorrect. I got same hashCode for the following two vectors:

com.ardor3d.math.Vector3 [X=9.256236796126904, Y=-105.2872465035467, Z=44.18433312431482]
com.ardor3d.math.Vector3 [X=-9.143763203873094, Y=-105.2872465035467, Z=44.18433312431482]

```
    @Override
    public int hashCode() {
        int result = 17;

        final long x = Double.doubleToLongBits(getX());
        result += 31 * result + (int) (x ^ x >>> 32);

        final long y = Double.doubleToLongBits(getY());
        result += 31 * result + (int) (y ^ y >>> 32);

        final long z = Double.doubleToLongBits(getZ());
        result += 31 * result + (int) (z ^ z >>> 32);

        return result;
    }
```

To fix this you can change the above Vector3.hashCode() method to this:

```
    @Override
    public int hashCode() {
        return Objects.hashCode(_x, _y, _z);
    }
```

Other hashcode methods in other classes may have similar problems but I didn't test those.

**Comment by gouessej** [comment]
At first, it's rather Objects.hash(_x, _y, _z). Secondly, keep in mind that "It is not required that if two objects are unequal according to the equals(java.lang.Object) method, then calling the hashCode method on each of the two objects must produce distinct integer results". If your suggestion produces more consistent hash codes with less code, I will use it but the class java.lang.Objects is only available in Java 1.7 and later whereas there are still a very few JogAmp's Ardor3D Continuation users using Java 1.6. Maybe we can do it later when I will really switch to Java 1.6. What's your opinion?

**Comment by runiter** [comment]
Oops you're right, it's Objects.hash()
You're also right that Objects.hash() is Java 1.7 but it seem to simply call Arrays.hashCode(values) which has been there since Java 1.5 so you could use that instead to be compatible to Java 1.5+.

**Comment by gouessej** [comment]
Actually, I don't remember exactly who was still using JogAmp's Ardor3D Continuation with Java 1.6, I'll probably move to Java 1.7 in a few weeks, I'll change that:
https://github.com/gouessej/Ardor3D/blob/master/pom.xml#L135

I'd like to use Objects.equals() too.

**Comment by runiter** [comment]
It would actually be nice to keep support for Java 1.6 a little longer since there are still lots of older Mac computers around that rely on Apple Java and cannot upgrade to Oracle Java.

**Comment by gouessej** [comment]
JogAmp's Ardor3D Continuation doesn't support Apple Java. Moreover, Apple Java has been deprecated (by Apple) for years. Apple itself claims that its laptops are designed to last 3 years. If some Apple users want to offer a second life to their Macs, they should switch to GNU Linux. If they expect a computer to last more than 3 years in excellent conditions with software upgrades, they should clearly not use OS X anyway. I advise the developers who care about OS X users to bundle OpenJDK with their software(s), it's very easy with JNDT (Java Native Deployment Toolkit). Relying on the JRE installed on the system has become increasingly painful. Applets are deprecated in Java 1.9 and will be removed in Java 1.10, Java Webstart is mostly unusable without "trusted" certificates, the system JRE isn't very useful. I succeeded in running OpenJDK 1.7 under OS X 10.7. I'm worried about planned obsolescence but the best thing I can do for OS X users with old Macs is to advise them to use another operating system.

Finally, (JogAmp's) Java3D (Continuation) 1.7.0 drops Java 1.6 support, it's time to do the same for JogAmp's Ardor3D Continuation too.

**Comment by runiter** [comment]
Sure, that makes sense.

**Comment by gouessej** [comment]
I'm currently "fixing" this "bug" but I repeat it once again: "It is not required that if two objects are unequal according to the equals(java.lang.Object) method, then calling the hashCode method on each of the two objects must produce distinct integer results". The new implementation will provide "better" hash codes in your case but the previous implementation wasn't wrong, returning the same hash code for two different objects is legal, you cannot always find a bijective method so that different objects always have different hash codes.

**Comment by gouessej** [comment]
Fixed in this commit: https://github.com/gouessej/Ardor3D/commit/ced8e5e5a3439630b51a5aef53ef5dfbde69eb95

**Comment by runiter** [comment]
You're right. Even with my own suggestion I still got hash collision so I ended up finding another algorithm that doesn't need hash maps.
